import { jsonError } from "@/lib/server/api-response";

export type SessionRequestInput = {
  alwaysAllowedPackage?: string;
  dailyLimitMinutes: number;
  deviceName: string;
  forcedSleepEnabled: boolean;
  fullDiscretion: boolean;
  galleryAccessEnabled: boolean;
  screenTimeEnabled: boolean;
  sessionDays: number;
};

export type ApproveSessionRequestInput = {
  dailyLimitMinutes?: number;
  forcedSleepEnabled?: boolean;
  galleryAccessEnabled?: boolean;
  sessionDays?: number;
};

export type ActivateInput = {
  timezone?: string;
  // Best-effort, client-reported reason the device's *previous* local session disappeared (see
  // SessionClearReasonSupport.kt) -- surfaced to the keyholder so she doesn't have to rely on the
  // sub accurately relaying on-screen text. Purely informational, never validated against
  // anything server-side.
  lastSessionClearAt?: string;
  lastSessionClearReason?: string;
};

export type RegisterInput = {
  deviceName: string;
  // Optional: required only for a genuinely new registration. If hardwareIdHash matches an
  // existing device (see /api/register), the existing username is reused and this is ignored.
  username?: string;
  timezone?: string;
  // Hash of Android's ANDROID_ID -- stable across app uninstall/reinstall for the same device +
  // app signing key (only changes on factory reset), so losing the locally-stored device secret
  // doesn't force a paid/approved sub to register a brand new account from scratch.
  hardwareIdHash?: string;
  // Generated by Android once per registration flow. Reusing it across retries makes recovery
  // idempotent if the backend committed an earlier request but its response never reached the
  // device. The backend stores only its hash.
  deviceSecret?: string;
  // Self-reported Build.* values, purely informational (never validated against anything, no
  // access control depends on them) -- lets the keyholder see what device/OS a sub is on without
  // asking. Any of these being missing/malformed just means the dashboard shows less, not an error.
  deviceManufacturer?: string;
  deviceModel?: string;
  androidRelease?: string;
  androidSdkInt?: number;
};

export type FcmTokenInput = {
  fcmToken: string;
};

export type DeviceLocationInput = {
  accuracyMeters?: number;
  latitude: number;
  longitude: number;
};

export type DnsQueryLogEntryInput = {
  blocked: boolean;
  domain: string;
  queriedAt: string;
};

export type DnsQueryLogInput = {
  queries: DnsQueryLogEntryInput[];
};

export type CrashReportInput = {
  appVersionCode?: number;
  appVersionName?: string;
  deviceModel?: string;
  exceptionSummary: string;
  osVersion?: string;
  stackTrace?: string;
  // Which bracketed operation (see OperationStageTracking.kt) hadn't finished yet at the moment
  // of the crash, if any -- e.g. "forced_sleep"/"lock_now". Purely informational.
  crashedDuringFeature?: string;
  crashedDuringStage?: string;
};

export type SessionMessageInput = {
  body: string;
};

export type AppUnlockRequestInput = {
  packageName: string;
};

export type InstalledAppEntryInput = {
  appName: string;
  packageName: string;
};

export type InstalledAppsReportInput = {
  apps: InstalledAppEntryInput[];
};

export type SettingsPinInput = {
  pin: string;
};

export type HeartbeatInput = {
  accessibilityGranted?: boolean;
  accessibilityRunning?: boolean;
  activeSessionPresent?: boolean;
  autostartAcknowledged?: boolean;
  batteryOptimizationIgnored?: boolean;
  blockingActive?: boolean;
  blockingMethod?: string;
  blockingRequired?: boolean;
  dailyLimitMinutes?: number;
  debuggerAttached?: boolean;
  deviceAdminGranted?: boolean;
  deviceId?: string;
  deviceName: string;
  emulatorDetected?: boolean;
  forcedSleepEnabled?: boolean;
  forcedSleepReady?: boolean;
  insideSleepWindow?: boolean;
  insidePersistencePenalty?: boolean;
  persistencePenaltyUntil?: string;
  lastAccessibilityEventAt?: string;
  lastProtectionTickAt?: string;
  lastRemoteActionCheckAt?: string;
  lastRecoveryAttemptAt?: string;
  lastRecoveryReason?: string;
  lastSessionSyncAt?: string;
  lastProtectionCheckAt?: string;
  lastUsageRefreshAt?: string;
  limitReached?: boolean;
  localDate?: string;
  networkConnected?: boolean;
  notificationAccessGranted?: boolean;
  activityRecognitionGranted?: boolean;
  overlayActive?: boolean;
  overlayPermissionGranted?: boolean;
  overlayReady?: boolean;
  pollingIntervalMs?: number;
  pollingMode?: string;
  foregroundServiceRunning?: boolean;
  protectionBrokenReasons?: string[];
  protectionHealthy?: boolean;
  protectionHealthLevel?: string;
  protectionHealthStatus?: string;
  protectionState: string;
  remainingMinutes?: number;
  serviceRunning?: boolean;
  sessionId: string;
  sessionStatus: string;
  timezone?: string;
  perAppMinutes?: Record<string, number>;
  remoteActionQueueLength?: number;
  rootDetected?: boolean;
  stepBonusMinutesEarnedToday?: number;
  stepsToday?: number;
  usageAccessGranted?: boolean;
  usedMinutes?: number;
  appVersion?: string;
  // Self-reported Build.* values, same as RegisterInput -- sent on every heartbeat (not just
  // registration) so an OS update or a device that registered before this existed both get
  // picked up here instead of being stuck with a stale/missing value forever.
  deviceManufacturer?: string;
  deviceModel?: string;
  androidRelease?: string;
  androidSdkInt?: number;
  // Set only if the previous app process began a bracketed operation (see
  // OperationStageTracking.kt) and never finished it -- i.e. the process died mid-operation.
  // Cleared client-side once a heartbeat carrying it is confirmed sent, so this only shows up
  // once per actual failure, not on every heartbeat forever.
  lastFailedFeature?: string;
  lastFailedStage?: string;
  lastFailedDetectedAt?: string;
};

export type RemoteActionCreateInput = {
  actionType:
    | "capture_gallery"
    | "capture_screenshot"
    | "clear_local_usage"
    | "force_lock"
    | "set_wallpaper"
    | "sync_config";
  deviceId?: string;
  payload?: Record<string, unknown>;
  sessionId: string;
};

export type RemoteActionCompleteInput = {
  errorMessage?: string;
  ok: boolean;
  result?: Record<string, unknown>;
};

export type WeekdayOverride = {
  dailyLimitMinutes?: number;
  sleepEndTime?: string;
  sleepStartTime?: string;
};

export type AdminSessionUpdateInput = {
  alwaysAllowedPackage?: string | null;
  blockedDomains?: string[];
  blockedPackages?: string[];
  contentFilterEnabled?: boolean;
  galleryAccessEnabled?: boolean;
  dailyLimitMinutes?: number;
  endsAt?: string;
  extendDays?: number;
  forcedSleepEnabled?: boolean;
  screenTimeEnabled?: boolean;
  sleepEndTime?: string;
  sleepStartTime?: string;
  status?: "revoked";
  stepRewardBonusMinutes?: number;
  stepRewardEnabled?: boolean;
  stepRewardStepsRequired?: number;
  weekdayOverrides?: Record<string, WeekdayOverride>;
};

const WEEKDAY_KEYS = new Set(["mon", "tue", "wed", "thu", "fri", "sat", "sun"]);
const PACKAGE_NAME_REGEX = /^[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)+$/;

function isProtectedSystemPackage(packageName: string) {
  const normalized = packageName.trim().toLowerCase();
  return (
    normalized === "com.android.settings" ||
    normalized.includes("packageinstaller") ||
    normalized.includes("permissioncontroller") ||
    normalized.includes("securitycenter") ||
    normalized.includes("systemui")
  );
}

export async function readJsonBody<T>(request: Request) {
  try {
    return {
      ok: true as const,
      data: (await request.json()) as T,
    };
  } catch {
    return {
      ok: false as const,
      response: jsonError(400, "Invalid JSON request body."),
    };
  }
}

function isIntegerInRange(value: unknown, minimum: number, maximum: number) {
  return Number.isInteger(value) && Number(value) >= minimum && Number(value) <= maximum;
}

const TIME_VALUE_REGEX = /^([01]\d|2[0-3]):([0-5]\d)$/;

function normalizeRequiredString(value: unknown) {
  if (typeof value !== "string") {
    return null;
  }

  const normalized = value.trim();
  return normalized.length > 0 ? normalized : null;
}

export function validateSessionRequestInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const deviceName = normalizeRequiredString(payload.deviceName);

  if (!deviceName) {
    return { ok: false as const, response: jsonError(400, "deviceName is required.") };
  }

  if (payload.fullDiscretion !== undefined && typeof payload.fullDiscretion !== "boolean") {
    return { ok: false as const, response: jsonError(400, "fullDiscretion must be a boolean when provided.") };
  }

  // "Leave it up to Principessa" mode: the sub doesn't have to specify terms at all -- the
  // keyholder sets the real values freely when approving. Placeholders below only exist to
  // satisfy the not-null/check constraints on session_requests until then.
  const fullDiscretion = payload.fullDiscretion === true;

  if (!fullDiscretion) {
    if (!isIntegerInRange(payload.sessionDays, 1, 30)) {
      return { ok: false as const, response: jsonError(400, "sessionDays must be an integer between 1 and 30.") };
    }

    if (!isIntegerInRange(payload.dailyLimitMinutes, 5, 90)) {
      return {
        ok: false as const,
        response: jsonError(400, "dailyLimitMinutes must be an integer between 5 and 90."),
      };
    }

    if (typeof payload.forcedSleepEnabled !== "boolean") {
      return { ok: false as const, response: jsonError(400, "forcedSleepEnabled must be a boolean.") };
    }
  } else {
    if (payload.sessionDays !== undefined && !isIntegerInRange(payload.sessionDays, 1, 30)) {
      return { ok: false as const, response: jsonError(400, "sessionDays must be an integer between 1 and 30 when provided.") };
    }

    if (payload.dailyLimitMinutes !== undefined && !isIntegerInRange(payload.dailyLimitMinutes, 5, 90)) {
      return {
        ok: false as const,
        response: jsonError(400, "dailyLimitMinutes must be an integer between 5 and 90 when provided."),
      };
    }

    if (payload.forcedSleepEnabled !== undefined && typeof payload.forcedSleepEnabled !== "boolean") {
      return { ok: false as const, response: jsonError(400, "forcedSleepEnabled must be a boolean when provided.") };
    }
  }

  if (payload.galleryAccessEnabled !== undefined && typeof payload.galleryAccessEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "galleryAccessEnabled must be a boolean when provided.") };
  }

  if (payload.screenTimeEnabled !== undefined && typeof payload.screenTimeEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "screenTimeEnabled must be a boolean when provided.") };
  }

  const alwaysAllowedPackage = normalizeOptionalString(payload.alwaysAllowedPackage);

  if (
    alwaysAllowedPackage &&
    (!PACKAGE_NAME_REGEX.test(alwaysAllowedPackage) || isProtectedSystemPackage(alwaysAllowedPackage))
  ) {
    return {
      ok: false as const,
      response: jsonError(400, "alwaysAllowedPackage must be a selectable non-system Android package."),
    };
  }

  return {
    ok: true as const,
    data: {
      alwaysAllowedPackage: alwaysAllowedPackage ?? undefined,
      dailyLimitMinutes: Number(payload.dailyLimitMinutes ?? 30),
      deviceName,
      forcedSleepEnabled: (payload.forcedSleepEnabled as boolean | undefined) ?? false,
      fullDiscretion,
      galleryAccessEnabled: (payload.galleryAccessEnabled as boolean | undefined) ?? false,
      screenTimeEnabled: (payload.screenTimeEnabled as boolean | undefined) ?? true,
      sessionDays: Number(payload.sessionDays ?? 1),
    } satisfies SessionRequestInput,
  };
}

export function validateApproveSessionRequestInput(input: unknown) {
  if (input === undefined || input === null) {
    return { ok: true as const, data: {} satisfies ApproveSessionRequestInput };
  }

  if (typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object when provided.") };
  }

  const payload = input as Record<string, unknown>;
  const data: ApproveSessionRequestInput = {};

  if (payload.sessionDays !== undefined) {
    if (!isIntegerInRange(payload.sessionDays, 1, 30)) {
      return { ok: false as const, response: jsonError(400, "sessionDays must be an integer between 1 and 30 when provided.") };
    }

    data.sessionDays = Number(payload.sessionDays);
  }

  if (payload.dailyLimitMinutes !== undefined) {
    // Unlike validateSessionRequestInput (the sub-facing request form, still capped at 5-90),
    // this is the keyholder setting real terms at approval time -- what matters is who's making
    // the request, not a blanket cap, so this only enforces a sanity ceiling (24h).
    if (!isIntegerInRange(payload.dailyLimitMinutes, 5, 1440)) {
      return {
        ok: false as const,
        response: jsonError(400, "dailyLimitMinutes must be an integer between 5 and 1440 when provided."),
      };
    }

    data.dailyLimitMinutes = Number(payload.dailyLimitMinutes);
  }

  if (payload.forcedSleepEnabled !== undefined) {
    if (typeof payload.forcedSleepEnabled !== "boolean") {
      return { ok: false as const, response: jsonError(400, "forcedSleepEnabled must be a boolean when provided.") };
    }

    data.forcedSleepEnabled = payload.forcedSleepEnabled;
  }

  if (payload.galleryAccessEnabled !== undefined) {
    if (typeof payload.galleryAccessEnabled !== "boolean") {
      return { ok: false as const, response: jsonError(400, "galleryAccessEnabled must be a boolean when provided.") };
    }

    data.galleryAccessEnabled = payload.galleryAccessEnabled;
  }

  return { ok: true as const, data };
}

export function validateRegisterInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const deviceName = normalizeRequiredString(payload.deviceName);
  const usernameProvided = payload.username !== undefined;
  const username = normalizeRequiredString(payload.username);

  if (!deviceName) {
    return { ok: false as const, response: jsonError(400, "deviceName is required.") };
  }

  // Format is still enforced whenever a username is given -- only whether it's required at all
  // depends on hardwareIdHash resolving to an existing device, which the route decides (it needs
  // a DB lookup this validator doesn't have access to).
  if (usernameProvided && (!username || !/^[a-zA-Z0-9_]{3,20}$/.test(username))) {
    return {
      ok: false as const,
      response: jsonError(400, "username must be 3-20 characters using only letters, digits, and underscores."),
    };
  }

  if (payload.timezone !== undefined && normalizeRequiredString(payload.timezone) === null) {
    return { ok: false as const, response: jsonError(400, "timezone must be a non-empty string when provided.") };
  }

  if (payload.hardwareIdHash !== undefined && normalizeRequiredString(payload.hardwareIdHash) === null) {
    return { ok: false as const, response: jsonError(400, "hardwareIdHash must be a non-empty string when provided.") };
  }

  const deviceSecret = normalizeRequiredString(payload.deviceSecret);
  if (
    payload.deviceSecret !== undefined &&
    (!deviceSecret || !/^plock_[A-Za-z0-9_-]{43}$/.test(deviceSecret))
  ) {
    return {
      ok: false as const,
      response: jsonError(400, "deviceSecret must be a valid high-entropy device credential when provided."),
    };
  }

  // Purely informational (see RegisterInput comment) -- clamp length instead of rejecting, since
  // there's nothing to actually validate a Build.* string against and a malformed value shouldn't
  // fail the whole registration.
  const clampDeviceInfoString = (value: unknown) => normalizeRequiredString(value)?.slice(0, 100) ?? undefined;
  const androidSdkInt =
    typeof payload.androidSdkInt === "number" && Number.isInteger(payload.androidSdkInt) &&
    payload.androidSdkInt > 0 && payload.androidSdkInt < 1000
      ? payload.androidSdkInt
      : undefined;

  return {
    ok: true as const,
    data: {
      deviceName,
      username: username ?? undefined,
      timezone: normalizeRequiredString(payload.timezone) ?? undefined,
      hardwareIdHash: normalizeRequiredString(payload.hardwareIdHash) ?? undefined,
      deviceSecret: deviceSecret ?? undefined,
      deviceManufacturer: clampDeviceInfoString(payload.deviceManufacturer),
      deviceModel: clampDeviceInfoString(payload.deviceModel),
      androidRelease: clampDeviceInfoString(payload.androidRelease),
      androidSdkInt,
    } satisfies RegisterInput,
  };
}

export function validateFcmTokenInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const fcmToken = normalizeRequiredString(payload.fcmToken);

  if (!fcmToken) {
    return { ok: false as const, response: jsonError(400, "fcmToken is required.") };
  }

  return {
    ok: true as const,
    data: { fcmToken } satisfies FcmTokenInput,
  };
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

export function validateDeviceLocationInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;

  if (!isFiniteNumber(payload.latitude) || payload.latitude < -90 || payload.latitude > 90) {
    return { ok: false as const, response: jsonError(400, "latitude must be a number between -90 and 90.") };
  }

  if (!isFiniteNumber(payload.longitude) || payload.longitude < -180 || payload.longitude > 180) {
    return { ok: false as const, response: jsonError(400, "longitude must be a number between -180 and 180.") };
  }

  if (payload.accuracyMeters !== undefined && (!isFiniteNumber(payload.accuracyMeters) || payload.accuracyMeters < 0)) {
    return { ok: false as const, response: jsonError(400, "accuracyMeters must be a non-negative number when provided.") };
  }

  return {
    ok: true as const,
    data: {
      accuracyMeters: payload.accuracyMeters as number | undefined,
      latitude: payload.latitude,
      longitude: payload.longitude,
    } satisfies DeviceLocationInput,
  };
}

const DNS_QUERY_LOG_MAX_ENTRIES = 50;

export function validateDnsQueryLogInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;

  if (!Array.isArray(payload.queries)) {
    return { ok: false as const, response: jsonError(400, "queries must be an array.") };
  }

  if (payload.queries.length > DNS_QUERY_LOG_MAX_ENTRIES) {
    return { ok: false as const, response: jsonError(400, `queries must contain at most ${DNS_QUERY_LOG_MAX_ENTRIES} entries.`) };
  }

  const queries: DnsQueryLogEntryInput[] = [];

  for (const rawEntry of payload.queries) {
    if (!rawEntry || typeof rawEntry !== "object") {
      return { ok: false as const, response: jsonError(400, "Each query entry must be an object.") };
    }

    const entry = rawEntry as Record<string, unknown>;
    const domain = normalizeRequiredString(entry.domain);

    if (!domain) {
      return { ok: false as const, response: jsonError(400, "Each query entry requires a non-empty domain.") };
    }

    if (typeof entry.blocked !== "boolean") {
      return { ok: false as const, response: jsonError(400, "Each query entry requires a boolean blocked field.") };
    }

    const queriedAt = normalizeRequiredString(entry.queriedAt);

    if (!queriedAt) {
      return { ok: false as const, response: jsonError(400, "Each query entry requires a non-empty queriedAt timestamp.") };
    }

    queries.push({ blocked: entry.blocked, domain: domain.toLowerCase(), queriedAt });
  }

  return {
    ok: true as const,
    data: { queries } satisfies DnsQueryLogInput,
  };
}

const MAX_STACK_TRACE_CHARS = 8000;

export function validateCrashReportInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const exceptionSummary = normalizeRequiredString(payload.exceptionSummary);

  if (!exceptionSummary) {
    return { ok: false as const, response: jsonError(400, "exceptionSummary is required.") };
  }

  if (payload.appVersionCode !== undefined && !isFiniteNumber(payload.appVersionCode)) {
    return { ok: false as const, response: jsonError(400, "appVersionCode must be a number when provided.") };
  }

  return {
    ok: true as const,
    data: {
      appVersionCode: payload.appVersionCode as number | undefined,
      appVersionName: typeof payload.appVersionName === "string" ? payload.appVersionName.slice(0, 100) : undefined,
      deviceModel: typeof payload.deviceModel === "string" ? payload.deviceModel.slice(0, 200) : undefined,
      exceptionSummary: exceptionSummary.slice(0, 1000),
      osVersion: typeof payload.osVersion === "string" ? payload.osVersion.slice(0, 200) : undefined,
      stackTrace: typeof payload.stackTrace === "string" ? payload.stackTrace.slice(0, MAX_STACK_TRACE_CHARS) : undefined,
      crashedDuringFeature: typeof payload.crashedDuringFeature === "string" ? payload.crashedDuringFeature.slice(0, 100) : undefined,
      crashedDuringStage: typeof payload.crashedDuringStage === "string" ? payload.crashedDuringStage.slice(0, 100) : undefined,
    } satisfies CrashReportInput,
  };
}

export function validateSessionMessageInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const body = normalizeRequiredString(payload.body);

  if (!body) {
    return { ok: false as const, response: jsonError(400, "body is required.") };
  }

  if (body.length > 1000) {
    return { ok: false as const, response: jsonError(400, "body must be at most 1000 characters.") };
  }

  return {
    ok: true as const,
    data: { body } satisfies SessionMessageInput,
  };
}

export function validateAppUnlockRequestInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const packageName = normalizeRequiredString(payload.packageName);

  if (!packageName) {
    return { ok: false as const, response: jsonError(400, "packageName is required.") };
  }

  return {
    ok: true as const,
    data: { packageName } satisfies AppUnlockRequestInput,
  };
}

const INSTALLED_APPS_MAX_ENTRIES = 500;

export function validateInstalledAppsReportInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;

  if (!Array.isArray(payload.apps)) {
    return { ok: false as const, response: jsonError(400, "apps must be an array.") };
  }

  if (payload.apps.length > INSTALLED_APPS_MAX_ENTRIES) {
    return { ok: false as const, response: jsonError(400, `apps must contain at most ${INSTALLED_APPS_MAX_ENTRIES} entries.`) };
  }

  const apps: InstalledAppEntryInput[] = [];

  for (const rawEntry of payload.apps) {
    if (!rawEntry || typeof rawEntry !== "object") {
      return { ok: false as const, response: jsonError(400, "Each app entry must be an object.") };
    }

    const entry = rawEntry as Record<string, unknown>;
    const packageName = normalizeRequiredString(entry.packageName);
    const appName = normalizeRequiredString(entry.appName);

    if (!packageName || !appName) {
      return { ok: false as const, response: jsonError(400, "Each app entry requires a non-empty packageName and appName.") };
    }

    apps.push({ appName, packageName });
  }

  return {
    ok: true as const,
    data: { apps } satisfies InstalledAppsReportInput,
  };
}

export function validateSettingsPinInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const pin = normalizeRequiredString(payload.pin);

  if (!pin) {
    return { ok: false as const, response: jsonError(400, "pin is required.") };
  }

  return {
    ok: true as const,
    data: { pin } satisfies SettingsPinInput,
  };
}

export function validateActivateInput(input: unknown) {
  if (input !== undefined && (!input || typeof input !== "object")) {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = (input ?? {}) as Record<string, unknown>;

  if (payload.timezone !== undefined && normalizeRequiredString(payload.timezone) === null) {
    return { ok: false as const, response: jsonError(400, "timezone must be a non-empty string when provided.") };
  }

  return {
    ok: true as const,
    data: {
      lastSessionClearAt: normalizeOptionalString(payload.lastSessionClearAt) ?? undefined,
      lastSessionClearReason: normalizeOptionalString(payload.lastSessionClearReason) ?? undefined,
      timezone: normalizeRequiredString(payload.timezone) ?? undefined,
    } satisfies ActivateInput,
  };
}

function normalizeOptionalString(value: unknown) {
  if (value === undefined || value === null) {
    return undefined;
  }

  return normalizeRequiredString(value) ?? null;
}

function isOptionalBoolean(value: unknown) {
  return value === undefined || typeof value === "boolean";
}

function isOptionalNonNegativeInteger(value: unknown) {
  return value === undefined || (Number.isInteger(value) && Number(value) >= 0);
}

function isOptionalStringArray(value: unknown) {
  return value === undefined || (Array.isArray(value) && value.every((entry) => typeof entry === "string" && entry.trim().length > 0));
}

export function validateHeartbeatInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const sessionId = normalizeRequiredString(payload.sessionId);
  const deviceName = normalizeRequiredString(payload.deviceName);
  const sessionStatus = normalizeRequiredString(payload.sessionStatus);
  const protectionState = normalizeRequiredString(payload.protectionState);

  if (!sessionId) {
    return { ok: false as const, response: jsonError(400, "sessionId is required.") };
  }

  if (!deviceName) {
    return { ok: false as const, response: jsonError(400, "deviceName is required.") };
  }

  if (!sessionStatus) {
    return { ok: false as const, response: jsonError(400, "sessionStatus is required.") };
  }

  if (!protectionState) {
    return { ok: false as const, response: jsonError(400, "protectionState is required.") };
  }

  if (payload.deviceId !== undefined && normalizeRequiredString(payload.deviceId) === null) {
    return { ok: false as const, response: jsonError(400, "deviceId must be a non-empty string when provided.") };
  }

  if (payload.timezone !== undefined && normalizeRequiredString(payload.timezone) === null) {
    return { ok: false as const, response: jsonError(400, "timezone must be a non-empty string when provided.") };
  }

  if (payload.appVersion !== undefined && normalizeRequiredString(payload.appVersion) === null) {
    return { ok: false as const, response: jsonError(400, "appVersion must be a non-empty string when provided.") };
  }

  if (
    !isOptionalBoolean(payload.activeSessionPresent) ||
    !isOptionalBoolean(payload.accessibilityGranted) ||
    !isOptionalBoolean(payload.accessibilityRunning) ||
    !isOptionalBoolean(payload.forcedSleepEnabled) ||
    !isOptionalBoolean(payload.forcedSleepReady) ||
    !isOptionalBoolean(payload.insideSleepWindow) ||
    !isOptionalBoolean(payload.insidePersistencePenalty) ||
    !isOptionalBoolean(payload.usageAccessGranted) ||
    !isOptionalBoolean(payload.deviceAdminGranted) ||
    !isOptionalBoolean(payload.blockingRequired) ||
    !isOptionalBoolean(payload.blockingActive) ||
    !isOptionalBoolean(payload.overlayPermissionGranted) ||
    !isOptionalBoolean(payload.overlayReady) ||
    !isOptionalBoolean(payload.overlayActive) ||
    !isOptionalBoolean(payload.notificationAccessGranted) ||
    !isOptionalBoolean(payload.activityRecognitionGranted) ||
    !isOptionalBoolean(payload.autostartAcknowledged) ||
    !isOptionalBoolean(payload.networkConnected) ||
    !isOptionalBoolean(payload.limitReached) ||
    !isOptionalBoolean(payload.batteryOptimizationIgnored) ||
    !isOptionalBoolean(payload.protectionHealthy) ||
    !isOptionalBoolean(payload.serviceRunning) ||
    !isOptionalBoolean(payload.foregroundServiceRunning) ||
    !isOptionalBoolean(payload.rootDetected) ||
    !isOptionalBoolean(payload.emulatorDetected) ||
    !isOptionalBoolean(payload.debuggerAttached)
  ) {
    return { ok: false as const, response: jsonError(400, "Heartbeat boolean fields must be booleans when provided.") };
  }

  if (
    !isOptionalNonNegativeInteger(payload.usedMinutes) ||
    !isOptionalNonNegativeInteger(payload.dailyLimitMinutes) ||
    !isOptionalNonNegativeInteger(payload.remainingMinutes) ||
    !isOptionalNonNegativeInteger(payload.pollingIntervalMs) ||
    !isOptionalNonNegativeInteger(payload.remoteActionQueueLength) ||
    !isOptionalNonNegativeInteger(payload.stepsToday) ||
    !isOptionalNonNegativeInteger(payload.stepBonusMinutesEarnedToday)
  ) {
    return {
      ok: false as const,
      response: jsonError(400, "Heartbeat integer fields must be non-negative integers when provided."),
    };
  }

  if (payload.protectionHealthStatus !== undefined && normalizeRequiredString(payload.protectionHealthStatus) === null) {
    return { ok: false as const, response: jsonError(400, "protectionHealthStatus must be a non-empty string when provided.") };
  }

  if (payload.protectionHealthLevel !== undefined && normalizeRequiredString(payload.protectionHealthLevel) === null) {
    return { ok: false as const, response: jsonError(400, "protectionHealthLevel must be a non-empty string when provided.") };
  }

  if (!isOptionalStringArray(payload.protectionBrokenReasons)) {
    return { ok: false as const, response: jsonError(400, "protectionBrokenReasons must be a string array when provided.") };
  }

  if (payload.blockingMethod !== undefined && normalizeRequiredString(payload.blockingMethod) === null) {
    return { ok: false as const, response: jsonError(400, "blockingMethod must be a non-empty string when provided.") };
  }

  if (payload.lastProtectionCheckAt !== undefined && normalizeRequiredString(payload.lastProtectionCheckAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastProtectionCheckAt must be a non-empty string when provided.") };
  }

  if (payload.persistencePenaltyUntil !== undefined && normalizeRequiredString(payload.persistencePenaltyUntil) === null) {
    return { ok: false as const, response: jsonError(400, "persistencePenaltyUntil must be a non-empty string when provided.") };
  }

  if (payload.lastAccessibilityEventAt !== undefined && normalizeRequiredString(payload.lastAccessibilityEventAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastAccessibilityEventAt must be a non-empty string when provided.") };
  }

  if (payload.lastProtectionTickAt !== undefined && normalizeRequiredString(payload.lastProtectionTickAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastProtectionTickAt must be a non-empty string when provided.") };
  }

  if (payload.lastRemoteActionCheckAt !== undefined && normalizeRequiredString(payload.lastRemoteActionCheckAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastRemoteActionCheckAt must be a non-empty string when provided.") };
  }

  if (payload.lastRecoveryAttemptAt !== undefined && normalizeRequiredString(payload.lastRecoveryAttemptAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastRecoveryAttemptAt must be a non-empty string when provided.") };
  }

  if (payload.lastRecoveryReason !== undefined && normalizeRequiredString(payload.lastRecoveryReason) === null) {
    return { ok: false as const, response: jsonError(400, "lastRecoveryReason must be a non-empty string when provided.") };
  }

  if (payload.lastUsageRefreshAt !== undefined && normalizeRequiredString(payload.lastUsageRefreshAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastUsageRefreshAt must be a non-empty string when provided.") };
  }

  if (payload.lastSessionSyncAt !== undefined && normalizeRequiredString(payload.lastSessionSyncAt) === null) {
    return { ok: false as const, response: jsonError(400, "lastSessionSyncAt must be a non-empty string when provided.") };
  }

  if (payload.pollingMode !== undefined && normalizeRequiredString(payload.pollingMode) === null) {
    return { ok: false as const, response: jsonError(400, "pollingMode must be a non-empty string when provided.") };
  }

  if (payload.localDate !== undefined) {
    const localDate = normalizeRequiredString(payload.localDate);
    if (!localDate || !/^\d{4}-\d{2}-\d{2}$/.test(localDate)) {
      return { ok: false as const, response: jsonError(400, "localDate must use YYYY-MM-DD format when provided.") };
    }
  }

  let perAppMinutes: Record<string, number> | undefined;

  if (payload.perAppMinutes !== undefined) {
    if (typeof payload.perAppMinutes !== "object" || payload.perAppMinutes === null || Array.isArray(payload.perAppMinutes)) {
      return { ok: false as const, response: jsonError(400, "perAppMinutes must be a JSON object when provided.") };
    }

    perAppMinutes = {};
    let entryCount = 0;

    for (const [packageName, minutes] of Object.entries(payload.perAppMinutes as Record<string, unknown>)) {
      entryCount += 1;
      if (entryCount > 50) {
        return { ok: false as const, response: jsonError(400, "perAppMinutes must contain at most 50 entries.") };
      }

      if (typeof minutes !== "number" || !Number.isInteger(minutes) || minutes < 0) {
        return { ok: false as const, response: jsonError(400, `perAppMinutes.${packageName} must be a non-negative integer.`) };
      }

      perAppMinutes[packageName] = minutes;
    }
  }

  return {
    ok: true as const,
    data: {
      activeSessionPresent: payload.activeSessionPresent as boolean | undefined,
      accessibilityGranted: payload.accessibilityGranted as boolean | undefined,
      accessibilityRunning: payload.accessibilityRunning as boolean | undefined,
      appVersion: normalizeOptionalString(payload.appVersion) ?? undefined,
      autostartAcknowledged: payload.autostartAcknowledged as boolean | undefined,
      batteryOptimizationIgnored: payload.batteryOptimizationIgnored as boolean | undefined,
      blockingActive: payload.blockingActive as boolean | undefined,
      blockingMethod: normalizeOptionalString(payload.blockingMethod) ?? undefined,
      blockingRequired: payload.blockingRequired as boolean | undefined,
      dailyLimitMinutes: payload.dailyLimitMinutes as number | undefined,
      debuggerAttached: payload.debuggerAttached as boolean | undefined,
      deviceAdminGranted: payload.deviceAdminGranted as boolean | undefined,
      deviceId: normalizeOptionalString(payload.deviceId) ?? undefined,
      deviceName,
      emulatorDetected: payload.emulatorDetected as boolean | undefined,
      foregroundServiceRunning: payload.foregroundServiceRunning as boolean | undefined,
      forcedSleepEnabled: payload.forcedSleepEnabled as boolean | undefined,
      forcedSleepReady: payload.forcedSleepReady as boolean | undefined,
      insideSleepWindow: payload.insideSleepWindow as boolean | undefined,
      insidePersistencePenalty: payload.insidePersistencePenalty as boolean | undefined,
      persistencePenaltyUntil: normalizeOptionalString(payload.persistencePenaltyUntil) ?? undefined,
      lastAccessibilityEventAt: normalizeOptionalString(payload.lastAccessibilityEventAt) ?? undefined,
      lastProtectionTickAt: normalizeOptionalString(payload.lastProtectionTickAt) ?? undefined,
      lastRemoteActionCheckAt: normalizeOptionalString(payload.lastRemoteActionCheckAt) ?? undefined,
      lastRecoveryAttemptAt: normalizeOptionalString(payload.lastRecoveryAttemptAt) ?? undefined,
      lastRecoveryReason: normalizeOptionalString(payload.lastRecoveryReason) ?? undefined,
      lastProtectionCheckAt: normalizeOptionalString(payload.lastProtectionCheckAt) ?? undefined,
      lastSessionSyncAt: normalizeOptionalString(payload.lastSessionSyncAt) ?? undefined,
      lastUsageRefreshAt: normalizeOptionalString(payload.lastUsageRefreshAt) ?? undefined,
      limitReached: payload.limitReached as boolean | undefined,
      localDate: normalizeOptionalString(payload.localDate) ?? undefined,
      networkConnected: payload.networkConnected as boolean | undefined,
      notificationAccessGranted: payload.notificationAccessGranted as boolean | undefined,
      activityRecognitionGranted: payload.activityRecognitionGranted as boolean | undefined,
      overlayActive: payload.overlayActive as boolean | undefined,
      overlayPermissionGranted: payload.overlayPermissionGranted as boolean | undefined,
      overlayReady: payload.overlayReady as boolean | undefined,
      pollingIntervalMs: payload.pollingIntervalMs as number | undefined,
      pollingMode: normalizeOptionalString(payload.pollingMode) ?? undefined,
      protectionBrokenReasons: (payload.protectionBrokenReasons as string[] | undefined) ?? undefined,
      protectionHealthy: payload.protectionHealthy as boolean | undefined,
      protectionHealthLevel: normalizeOptionalString(payload.protectionHealthLevel) ?? undefined,
      protectionHealthStatus: normalizeOptionalString(payload.protectionHealthStatus) ?? undefined,
      protectionState,
      remainingMinutes: payload.remainingMinutes as number | undefined,
      serviceRunning: payload.serviceRunning as boolean | undefined,
      sessionId,
      sessionStatus,
      timezone: normalizeOptionalString(payload.timezone) ?? undefined,
      perAppMinutes,
      remoteActionQueueLength: payload.remoteActionQueueLength as number | undefined,
      rootDetected: payload.rootDetected as boolean | undefined,
      stepBonusMinutesEarnedToday: payload.stepBonusMinutesEarnedToday as number | undefined,
      stepsToday: payload.stepsToday as number | undefined,
      usageAccessGranted: payload.usageAccessGranted as boolean | undefined,
      usedMinutes: payload.usedMinutes as number | undefined,
      deviceManufacturer: normalizeOptionalString(payload.deviceManufacturer)?.slice(0, 100) ?? undefined,
      deviceModel: normalizeOptionalString(payload.deviceModel)?.slice(0, 100) ?? undefined,
      androidRelease: normalizeOptionalString(payload.androidRelease)?.slice(0, 100) ?? undefined,
      androidSdkInt:
        typeof payload.androidSdkInt === "number" && Number.isInteger(payload.androidSdkInt) &&
        payload.androidSdkInt > 0 && payload.androidSdkInt < 1000
          ? payload.androidSdkInt
          : undefined,
      lastFailedFeature: normalizeOptionalString(payload.lastFailedFeature)?.slice(0, 100) ?? undefined,
      lastFailedStage: normalizeOptionalString(payload.lastFailedStage)?.slice(0, 100) ?? undefined,
      lastFailedDetectedAt: normalizeOptionalString(payload.lastFailedDetectedAt)?.slice(0, 100) ?? undefined,
    } satisfies HeartbeatInput,
  };
}

const ALLOWED_REMOTE_ACTIONS = new Set([
  "force_lock",
  "clear_local_usage",
  "sync_config",
  "capture_screenshot",
  "set_wallpaper",
  "capture_gallery",
  "clear_persistence_penalty",
]);

export function validateRemoteActionCreateInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;
  const sessionId = normalizeRequiredString(payload.sessionId);
  const actionType = normalizeRequiredString(payload.actionType);

  if (!sessionId) {
    return { ok: false as const, response: jsonError(400, "sessionId is required.") };
  }

  if (!actionType || !ALLOWED_REMOTE_ACTIONS.has(actionType)) {
    return {
      ok: false as const,
      response: jsonError(
        400,
        "actionType must be one of: force_lock, clear_local_usage, sync_config, capture_screenshot, set_wallpaper, capture_gallery, clear_persistence_penalty.",
      ),
    };
  }

  if (payload.deviceId !== undefined && normalizeRequiredString(payload.deviceId) === null) {
    return { ok: false as const, response: jsonError(400, "deviceId must be a non-empty string when provided.") };
  }

  if (payload.payload !== undefined && (typeof payload.payload !== "object" || payload.payload === null || Array.isArray(payload.payload))) {
    return { ok: false as const, response: jsonError(400, "payload must be a JSON object when provided.") };
  }

  return {
    ok: true as const,
    data: {
      actionType: actionType as RemoteActionCreateInput["actionType"],
      deviceId: normalizeOptionalString(payload.deviceId) ?? undefined,
      payload: (payload.payload as Record<string, unknown> | undefined) ?? {},
      sessionId,
    } satisfies RemoteActionCreateInput,
  };
}

export function validateRemoteActionCompleteInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;

  if (typeof payload.ok !== "boolean") {
    return { ok: false as const, response: jsonError(400, "ok must be a boolean.") };
  }

  if (payload.result !== undefined && (typeof payload.result !== "object" || payload.result === null || Array.isArray(payload.result))) {
    return { ok: false as const, response: jsonError(400, "result must be a JSON object when provided.") };
  }

  if (payload.errorMessage !== undefined && normalizeRequiredString(payload.errorMessage) === null) {
    return { ok: false as const, response: jsonError(400, "errorMessage must be a non-empty string when provided.") };
  }

  return {
    ok: true as const,
    data: {
      errorMessage: normalizeOptionalString(payload.errorMessage) ?? undefined,
      ok: payload.ok,
      result: (payload.result as Record<string, unknown> | undefined) ?? {},
    } satisfies RemoteActionCompleteInput,
  };
}

export function validateAdminSessionUpdateInput(input: unknown) {
  if (!input || typeof input !== "object") {
    return { ok: false as const, response: jsonError(400, "Request body must be a JSON object.") };
  }

  const payload = input as Record<string, unknown>;

  if (Object.keys(payload).length === 0) {
    return { ok: false as const, response: jsonError(400, "At least one session field must be provided.") };
  }

  // Admin-facing (desktop "Save Config") -- only a sanity ceiling (24h), not the sub-facing
  // request form's 5-90 cap. What matters is who's making the request, not a blanket limit.
  if (payload.dailyLimitMinutes !== undefined && !isIntegerInRange(payload.dailyLimitMinutes, 5, 1440)) {
    return {
      ok: false as const,
      response: jsonError(400, "dailyLimitMinutes must be an integer between 5 and 1440."),
    };
  }

  if (payload.forcedSleepEnabled !== undefined && typeof payload.forcedSleepEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "forcedSleepEnabled must be a boolean when provided.") };
  }

  if (payload.screenTimeEnabled !== undefined && typeof payload.screenTimeEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "screenTimeEnabled must be a boolean when provided.") };
  }

  if (payload.alwaysAllowedPackage !== undefined && payload.alwaysAllowedPackage !== null) {
    const alwaysAllowedPackage = normalizeRequiredString(payload.alwaysAllowedPackage);
    if (
      !alwaysAllowedPackage ||
      !PACKAGE_NAME_REGEX.test(alwaysAllowedPackage) ||
      isProtectedSystemPackage(alwaysAllowedPackage)
    ) {
      return {
        ok: false as const,
        response: jsonError(400, "alwaysAllowedPackage must be null or a selectable non-system Android package."),
      };
    }
  }

  if (payload.sleepStartTime !== undefined) {
    const sleepStartTime = normalizeRequiredString(payload.sleepStartTime);
    if (!sleepStartTime || !TIME_VALUE_REGEX.test(sleepStartTime)) {
      return { ok: false as const, response: jsonError(400, "sleepStartTime must use HH:mm format when provided.") };
    }
  }

  if (payload.sleepEndTime !== undefined) {
    const sleepEndTime = normalizeRequiredString(payload.sleepEndTime);
    if (!sleepEndTime || !TIME_VALUE_REGEX.test(sleepEndTime)) {
      return { ok: false as const, response: jsonError(400, "sleepEndTime must use HH:mm format when provided.") };
    }
  }

  if (payload.endsAt !== undefined) {
    const endsAt = normalizeRequiredString(payload.endsAt);
    if (!endsAt || Number.isNaN(new Date(endsAt).getTime())) {
      return { ok: false as const, response: jsonError(400, "endsAt must be a valid timestamp when provided.") };
    }
  }

  if (payload.extendDays !== undefined && !isIntegerInRange(payload.extendDays, 1, 30)) {
    return { ok: false as const, response: jsonError(400, "extendDays must be an integer between 1 and 30.") };
  }

  if (payload.endsAt !== undefined && payload.extendDays !== undefined) {
    return { ok: false as const, response: jsonError(400, "Provide either endsAt or extendDays, not both.") };
  }

  if (payload.status !== undefined && payload.status !== "revoked") {
    return { ok: false as const, response: jsonError(400, "status can only be set to revoked.") };
  }

  if (payload.blockedPackages !== undefined) {
    if (
      !Array.isArray(payload.blockedPackages) ||
      payload.blockedPackages.some((entry) => typeof entry !== "string" || entry.trim().length === 0)
    ) {
      return {
        ok: false as const,
        response: jsonError(400, "blockedPackages must be an array of non-empty strings when provided."),
      };
    }
  }

  if (payload.blockedDomains !== undefined) {
    if (
      !Array.isArray(payload.blockedDomains) ||
      payload.blockedDomains.some((entry) => typeof entry !== "string" || entry.trim().length === 0)
    ) {
      return {
        ok: false as const,
        response: jsonError(400, "blockedDomains must be an array of non-empty strings when provided."),
      };
    }
  }

  if (payload.contentFilterEnabled !== undefined && typeof payload.contentFilterEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "contentFilterEnabled must be a boolean when provided.") };
  }

  if (payload.galleryAccessEnabled !== undefined && typeof payload.galleryAccessEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "galleryAccessEnabled must be a boolean when provided.") };
  }

  if (payload.stepRewardEnabled !== undefined && typeof payload.stepRewardEnabled !== "boolean") {
    return { ok: false as const, response: jsonError(400, "stepRewardEnabled must be a boolean when provided.") };
  }

  if (payload.stepRewardStepsRequired !== undefined && !isIntegerInRange(payload.stepRewardStepsRequired, 100, 50_000)) {
    return {
      ok: false as const,
      response: jsonError(400, "stepRewardStepsRequired must be an integer between 100 and 50000."),
    };
  }

  if (payload.stepRewardBonusMinutes !== undefined && !isIntegerInRange(payload.stepRewardBonusMinutes, 1, 180)) {
    return {
      ok: false as const,
      response: jsonError(400, "stepRewardBonusMinutes must be an integer between 1 and 180."),
    };
  }

  let weekdayOverrides: Record<string, WeekdayOverride> | undefined;

  if (payload.weekdayOverrides !== undefined) {
    if (typeof payload.weekdayOverrides !== "object" || payload.weekdayOverrides === null || Array.isArray(payload.weekdayOverrides)) {
      return { ok: false as const, response: jsonError(400, "weekdayOverrides must be a JSON object when provided.") };
    }

    weekdayOverrides = {};

    for (const [key, rawOverride] of Object.entries(payload.weekdayOverrides as Record<string, unknown>)) {
      if (!WEEKDAY_KEYS.has(key)) {
        return { ok: false as const, response: jsonError(400, `weekdayOverrides key "${key}" must be one of: mon, tue, wed, thu, fri, sat, sun.`) };
      }

      if (typeof rawOverride !== "object" || rawOverride === null || Array.isArray(rawOverride)) {
        return { ok: false as const, response: jsonError(400, `weekdayOverrides.${key} must be a JSON object.`) };
      }

      const override = rawOverride as Record<string, unknown>;
      const parsedOverride: WeekdayOverride = {};

      if (override.dailyLimitMinutes !== undefined) {
        if (!isIntegerInRange(override.dailyLimitMinutes, 5, 1440)) {
          return { ok: false as const, response: jsonError(400, `weekdayOverrides.${key}.dailyLimitMinutes must be an integer between 5 and 1440.`) };
        }
        parsedOverride.dailyLimitMinutes = override.dailyLimitMinutes as number;
      }

      if (override.sleepStartTime !== undefined) {
        const sleepStartTime = normalizeRequiredString(override.sleepStartTime);
        if (!sleepStartTime || !TIME_VALUE_REGEX.test(sleepStartTime)) {
          return { ok: false as const, response: jsonError(400, `weekdayOverrides.${key}.sleepStartTime must use HH:mm format.`) };
        }
        parsedOverride.sleepStartTime = sleepStartTime;
      }

      if (override.sleepEndTime !== undefined) {
        const sleepEndTime = normalizeRequiredString(override.sleepEndTime);
        if (!sleepEndTime || !TIME_VALUE_REGEX.test(sleepEndTime)) {
          return { ok: false as const, response: jsonError(400, `weekdayOverrides.${key}.sleepEndTime must use HH:mm format.`) };
        }
        parsedOverride.sleepEndTime = sleepEndTime;
      }

      weekdayOverrides[key] = parsedOverride;
    }
  }

  return {
    ok: true as const,
    data: {
      alwaysAllowedPackage:
        payload.alwaysAllowedPackage === null
          ? null
          : normalizeOptionalString(payload.alwaysAllowedPackage) ?? undefined,
      blockedDomains: (payload.blockedDomains as string[] | undefined)?.map((entry) => entry.trim().toLowerCase()),
      blockedPackages: (payload.blockedPackages as string[] | undefined)?.map((entry) => entry.trim()),
      contentFilterEnabled: payload.contentFilterEnabled as boolean | undefined,
      galleryAccessEnabled: payload.galleryAccessEnabled as boolean | undefined,
      dailyLimitMinutes: payload.dailyLimitMinutes as number | undefined,
      endsAt: normalizeOptionalString(payload.endsAt) ?? undefined,
      extendDays: payload.extendDays as number | undefined,
      forcedSleepEnabled: payload.forcedSleepEnabled as boolean | undefined,
      screenTimeEnabled: payload.screenTimeEnabled as boolean | undefined,
      sleepEndTime: normalizeOptionalString(payload.sleepEndTime) ?? undefined,
      sleepStartTime: normalizeOptionalString(payload.sleepStartTime) ?? undefined,
      stepRewardBonusMinutes: payload.stepRewardBonusMinutes as number | undefined,
      stepRewardEnabled: payload.stepRewardEnabled as boolean | undefined,
      stepRewardStepsRequired: payload.stepRewardStepsRequired as number | undefined,
      weekdayOverrides,
      status: (payload.status as "revoked" | undefined) ?? undefined,
    } satisfies AdminSessionUpdateInput,
  };
}
